name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x  # Specify Node.js version 12.x

    - name: Install Dependencies
      run: npm install

    - name: Build Production App
      run: npm run build
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'